# Generated by Django 4.1.7 on 2023-03-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_landinfo_area_alter_landinfo_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinfo',
            name='name',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
