# Generated by Django 4.1.7 on 2023-03-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_landinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
